version: '3'

services:
  redis:
    image: redis/redis-stack:edge
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
  http_redis:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    ports:
      - '3000:3000'
    environment:
      SR_TOKEN: token
      REDIS_URL: redis://redis:6379

volumes:
  redis_data:
